import 'package:freezed_annotation/freezed_annotation.dart';
part 'info_cnpj_entity.freezed.dart';

@freezed
class InfoCnpjEntity with _$InfoCnpjEntity {
  const factory InfoCnpjEntity({
    required String uf,
    required String cep,
    required String cnpj,
    required String porte,
    required String bairro,
    required String numero,
    required String dddFax,
    required String municipio,
    required String logradouro,
    required int cnaeFiscal,
    required String complemento,
    required int codPorte,
    required String razaoSocial,
    required String nomeFantasia,
    required int capitalSocial,
    required String dddTelefone1,
    required String dddTelefone2,
    required bool opcaoPeloMei,
    required String descPorte,
    required int codMunicipio,
    required String naturezaJuridica,
    required String situacaoEspecial,
    required bool opcaoPeloSimples,
    required int situacaoCadastral,
    required String dataOpcaoPeloMei,
    required String dataExclusaoDoMei,
    required String cnaeFiscalDescricao,
    required int codMunicipioIbge,
    required String dataInicioAtividade,
    required String dataOpcaoPeloSimples,
    required String dataSituacaoCadastral,
    required String nomeCidadeNoExterior,
    required int codNaturezaJuridica,
    required String dataExclusaoDoSimples,
    required int motivoSituacaoCadastral,
    required int identificadorMatrizFilial,
    required int qualificacaoDoResponsavel,
    required String descSituacaoCadastral,
    required String descTipoDeLogradouro,
    required String descMotivoSituacaoCadastral,
    required String descIdentificadorMatrizFilial,
  }) = _InfoCnpjEntity;

  factory InfoCnpjEntity.empty() {
    return const InfoCnpjEntity(
      uf: '',
      cep: '',
      cnpj: '',
      porte: '',
      bairro: '',
      numero: '',
      dddFax: '',
      municipio: '',
      logradouro: '',
      cnaeFiscal: 0,
      complemento: '',
      codPorte: 0,
      razaoSocial: '',
      nomeFantasia: '',
      capitalSocial: 0,
      dddTelefone1: '',
      dddTelefone2: '',
      opcaoPeloMei: false,
      descPorte: '',
      codMunicipio: 0,
      naturezaJuridica: '',
      situacaoEspecial: '',
      opcaoPeloSimples: false,
      situacaoCadastral: 0,
      dataOpcaoPeloMei: '',
      dataExclusaoDoMei: '',
      cnaeFiscalDescricao: '',
      codMunicipioIbge: 0,
      dataInicioAtividade: '',
      dataOpcaoPeloSimples: '',
      dataSituacaoCadastral: '',
      nomeCidadeNoExterior: '',
      codNaturezaJuridica: 0,
      dataExclusaoDoSimples: '',
      motivoSituacaoCadastral: 0,
      identificadorMatrizFilial: 0,
      qualificacaoDoResponsavel: 0,
      descSituacaoCadastral: '',
      descTipoDeLogradouro: '',
      descMotivoSituacaoCadastral: '',
      descIdentificadorMatrizFilial: '',
    );
  }
}
